
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chtrwzvombtrpoghztaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNodHJ3enZvbWJ0cnBvZ2h6dGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTM4MjcsImV4cCI6MjA1OTQyOTgyN30.LXClkzCutGmNY4rQIp2btdaEoSUCUM1N4O_JebWIat0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
